# Generated by Django 4.1.3 on 2022-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('stack', models.CharField(max_length=200)),
            ],
        ),
    ]
