# Generated by Django 4.1.3 on 2023-09-09 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('about', models.TextField()),
                ('stack', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
