# Generated by Django 4.1.3 on 2022-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
