# Generated by Django 4.1.3 on 2022-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_created_project_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('started', models.DateTimeField(auto_now_add=True, null=True)),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
