# Generated by Django 4.1.3 on 2022-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_project_completed_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
