# Generated by Django 4.1.3 on 2022-12-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience_is_active_alter_experience_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media'),
        ),
    ]
