# Generated by Django 4.1.3 on 2022-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
