# Generated by Django 4.1.3 on 2022-12-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_experience_ended_alter_experience_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
