# Generated by Django 4.1.3 on 2023-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_experience_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
