# Generated by Django 4.1.3 on 2023-05-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_experience_ended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-started']},
        ),
    ]
