# Generated by Django 4.1.3 on 2023-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_experience_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started',
            field=models.DateField(),
        ),
    ]
