# Generated by Django 4.1.3 on 2023-09-07 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_created_alter_project_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
